services:
  zephyr_apps:
    user: "${HOST_UID}:${HOST_GID}"
    build: .
    image: zephyr-dev-setup:1.1
    working_dir: /workdir
    volumes:
      - ./:/workdir 
      - $HOME/.ssh:/root/.ssh:ro # Mount SSH keys for git access    devices:
      - /dev/bus/usb    command: sleep infinity
