services:
  zephyr_apps:
    user: "${HOST_UID}:${HOST_GID}"
    build: .
    image: zephyr-dev-setup:1.0
    working_dir: /workdir
    volumes:
      - $HOME/git/zephyr-apps:/workdir
      - $HOME/.ssh:/root/.ssh:ro \
    command: sleep infinity
